### ISSUE TITLE
Microsoft Sabotage & EdgeDeflector Discontinuation

### ISSUE THREAD

**Issue by Malix-Off** [MarcGuiselin/chrometana-pro#11]
Hello
I have just seen that [EdgeDeflector](https://github.com/da2x/EdgeDeflector) [was just discontinued](https://github.com/da2x/EdgeDeflector/commit/23ab3f6c12f3dd56be629a93d247fbe5a4fe62a6).
I think [this sabotage ](https://www.ctrl.blog/entry/microsoft-edge-protocol-competition.html) will also affect this project as well, is that correct?
Thanks!

**Comment by MarcGuiselin** [comment]
A little late, but yes the sabotage did affect this extension and broke it for everyone.

I've decided to update chrometana pro to use [Wedge](https://github.com/MarcGuiselin/wedge), my own edge link redirector that works on all versions of windows 10 and 11.
