### ISSUE TITLE
OperaTana

### ISSUE THREAD

**Issue by yodaluca23** [MarcGuiselin/chrometana-pro#7]
Please add this extension to the Opera Web Store It's on Chrome and Firefox already please make a branch for Opera. I have tried using the one from the chrome web store but it does not work D:

**Comment by MarcGuiselin** [comment]
You must enable "Allow access to search page results" in the opera://extensions settings page as shown below.
![image](https://user-images.githubusercontent.com/24906387/135188281-80c5244d-9632-482b-a6cd-2a47300b4abc.png)

Sometime in the near future, I'll look into creating a custom extension for opera that instructs installers to enable that setting.
